name: ci

on: [ push ]

permissions:
  contents: read

env:
  NODE_VERSION: "20"

jobs:
  ci-ChromeExtension:
    name: Chrome extension CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chrome-extension
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: 'chrome-extension/yarn.lock'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint the code
        run: yarn run lint

      - name: Build the code
        run: yarn run build
